<a href="https://colab.research.google.com/github/VirendraMane-cmyk/DISCOASS/blob/main/00_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

First time using pytorch

In [36]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)

2.2.1+cu121


##Tensors
##Way to represent multidimensional numeric **data**

In [37]:
#scalar
## Torch is not installed yet install using
!pip install torch

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 23.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 41.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 39.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 853.9 kB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 2.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 8.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 13.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 6.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 2.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.0/166.0 MB 2.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 11.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 64.0 MB/s eta 0:00:00


In [38]:
import torch


In [39]:
#scalar
scalar = torch.tensor(7)
scalar





tensor(7)

In [40]:
scalar.item()

7

In [41]:
#Vector

vector = torch.tensor([7,7])

vector

tensor([7, 7])

In [42]:
vector.ndim

1

In [43]:
vector.shape

torch.Size([2])

In [44]:
#MATRIX
MATRIX = torch.tensor([[7,8],[9,10]]);

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [45]:
MATRIX.ndim

2

In [46]:
MATRIX.shape

torch.Size([2, 2])

In [47]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [48]:
TENSOR.ndim

3

In [49]:
TENSOR.shape

torch.Size([1, 3, 3])

In [50]:
TENSOR.shape

torch.Size([1, 3, 3])

Creating Random Tensors

In [51]:
#Vectors and scalars are typically represented in lowercase
#Matric and tensors are uppercase
# Create a random tensor
# of size 3,4

random_tensor = torch.rand(3,4)

random_tensor


tensor([[0.1110, 0.9022, 0.3492, 0.6141],
        [0.3463, 0.7454, 0.1691, 0.3534],
        [0.3846, 0.5179, 0.3659, 0.7645]])

In [52]:
# Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(224,224,3) #height,width, color
#channels (R,G,B)

#Split the image in color channels to represent it in tensors

In [53]:
random_tensor.ndim

2

Zeros and ones

In [54]:
zeroes = torch.zeros(size = (3,4))

zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [55]:
zeroes*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [56]:
ones = torch.ones(3,4)

ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [57]:
ones.dtype

torch.float32

In [58]:
#Deafault data type in pytorch is float

Creating a range of tensors and tensors_like

In [59]:
one_to_ten  = torch.arange(1,1000,77) #(start,end,step)
#Will finish at end - 1

one_to_ten

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [60]:
#Creating tensors like

zoro = torch.zeros_like(one_to_ten)

zoro

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [61]:
#dtype = what datatype the tensor is
#float32 -> takes 32 bits to represent the tensor
#device->what device is your tensor on

#requires_gradient
float_32_tensor = torch.rand(4,5)

In [62]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([[0.0305, 0.6196, 0.9268, 0.2732, 0.6411],
        [0.0766, 0.2937, 0.8213, 0.3503, 0.5327],
        [0.7148, 0.3533, 0.2339, 0.2515, 0.6279],
        [0.0293, 0.4993, 0.5679, 0.4778, 0.9062]], dtype=torch.float16)

In [63]:
float_16_tensor*float_32_tensor

tensor([[9.3202e-04, 3.8403e-01, 8.5892e-01, 7.4632e-02, 4.1104e-01],
        [5.8693e-03, 8.6254e-02, 6.7439e-01, 1.2272e-01, 2.8374e-01],
        [5.1103e-01, 1.2481e-01, 5.4703e-02, 6.3220e-02, 3.9433e-01],
        [8.5663e-04, 2.4928e-01, 3.2234e-01, 2.2825e-01, 8.2113e-01]])

In [64]:
int_32 = torch.tensor([3,6,9],dtype = torch.int32)
int_32

tensor([3, 6, 9], dtype=torch.int32)

In [65]:
### To get dtype from tensor - Use tensor.dtype
### TO get shape -> tensor.shape

In [66]:
#Create a tensor
import torch

some_tensor = torch.rand(3,4)

some_tensor

print(some_tensor)

print(f"Datatype of tensor; {some_tensor.dtype}")

print(f"Shape of tensor; {some_tensor.shape}")

print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.5950, 0.3732, 0.5792, 0.1401],
        [0.2304, 0.6741, 0.8629, 0.9168],
        [0.0533, 0.1033, 0.4987, 0.6918]])
Datatype of tensor; torch.float32
Shape of tensor; torch.Size([3, 4])
Device tensor is on: cpu


Tensor Operations

1.Addition
2.Subtraction
3.Division
4.Multiplication
5.Matrix Multiplication

In [67]:
tensor = torch.tensor([1,2,3])

tensor + 10

tensor * 10

tensor2 = torch.rand(1,3)

tensor2

tensor + tensor2

tensor([[1.0759, 2.2249, 3.8527]])

In [68]:
#Element wise multiplication
# Multiply number with every element in the tensor

In [69]:
print(tensor, "*", tensor)
print(f"Equals : {tensor* tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [70]:
torch.matmul(tensor,tensor)

tensor(14)

In [71]:
%%time
tensor = torch.rand(10000)
value = 0

for i in range(len(tensor)):
    value += tensor[i]*tensor[i]
print(value)

tensor(3319.4487)
CPU times: user 96.9 ms, sys: 969 µs, total: 97.8 ms
Wall time: 108 ms


In [72]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 633 µs, sys: 0 ns, total: 633 µs
Wall time: 12.7 ms


tensor(3319.4556)

### Follow matrix rules while multiplying tensors

In [73]:
tensor_A = torch.rand(3,2)

tensor_B = torch.rand(3,2)

##torch.mm(tensor_A,tensor_B)

###Need to fix the shapes for multiplication


###Tranpose can be used

In [74]:
tensor_B.T

tensor([[0.9418, 0.5679, 0.1746],
        [0.7877, 0.1937, 0.0638]])

In [75]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[0.9277, 0.4336, 0.1352],
        [1.1947, 0.4721, 0.1489],
        [0.6038, 0.3508, 0.1080]])

In [76]:
torch.matmul(tensor_A,tensor_B.T).shape

torch.Size([3, 3])

The matrix multiplication will work when B is transposed **bold text**

##Find the min,max,mean,sum etc

In [77]:
x = torch.arange(0,100,10)

x


torch.min(x),x.min()

torch.max(x),x.max()



(tensor(90), tensor(90))

In [78]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [79]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

##Finding the postional min and max

In [80]:
x.argmin()

tensor(0)

In [81]:
x.argmax()

tensor(9)

## Reshaping

In [82]:
import torch

x = torch.arange(1.,10.)

x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [84]:
x_reshape = x.reshape(3,3)
x_reshape

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [85]:
# Change the view
z = x.view(1,9)

z,z.shape



(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [86]:
z[0] = 11
z,x

(tensor([[11., 11., 11., 11., 11., 11., 11., 11., 11.]]),
 tensor([11., 11., 11., 11., 11., 11., 11., 11., 11.]))